packages:
  - packages/*
  - website
overrides:
  react: ^19.2.7
  react-dom: ^19.2.7
  react-is: ^19.2.7
  typescript: ^7.0.2
  safer-buffer: npm:@nolyfill/safer-buffer@^1
engineStrict: true
allowBuilds:
  "@tailwindcss/oxide": true
  lefthook: true
minimumReleaseAge: 600
minimumReleaseAgeExclude:
  - "@resolid/*"
